# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App

  pod 'SwiftLint'
  pod 'R.swift'
  pod 'Moya', '~> 13.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'Cosmos', '~> 20.0'

  target 'AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppUITests' do
    # Pods for testing
  end

end
